language: node_js
node_js: node
after_success:
  - npm run report-cov
deploy: # Travis will remove the dist/ folder before deploy if we don't include this
  skip_cleanup: true
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 6317......16ef
    secure: EJoI9PqrCc2jNj2TYGYGgRzac0niz0Xf89lOWq97yBKrdJ1zK1wPpw7Nn43WHE+XmOUvg9UezPj2NcrZzkszelHgT+IlUm2LQpgVFlVlVn+MSKbCcfijk5MhbMYN+kkaiBMhiS9BCVQBImqe+Lz4GbOtoXpXVaE08i9wHlupEOHmUviUsM7FhNLl93wZjLn5sx0BVMM24O0R5gPwHe3NEabYEGLErXQ2YmnEZtgaBsxb+FPTo+txVp6EmSeG36RzXOsq+G8nKV3jvPdiI15KHzmWs7I31j8UMazLuydRxYKPOjvFp59a1yQHRcTnfxcEJWrQM9CndW0sfZWRfJZERkwdM00V/0FDCPtuQHtPvVNr61UFGQv9q5piRBLtM7xACBh6QD4tMacs1Mw1rpcY7gaWVVUNSTYqFmTE/kHUehQyeVLTMLvFHUohAHQ1zxhZ3Z+OQFxQxYcox/xJ4IQA/R4CfNrCOGDTPLhNKiNK6+QlPLf7L7I72ywFkKkfgF/vW4UfIfDIs/gWmiB55PHeU1dqjOXHT5ztaqu6nFpXab2vOqW3KZ2nHmtwXVk/9LafwAhPjBrNuk1AYshVhZ9N6iPUadHzRaKMoEfjGaEWAmhGPqtzbF/F8i46Bid+mRvEE8XzSPa6ZUS60lt5xS+12wbe4Q8KPIADM+xqtn4Zw48=
  on:
    tags: true
    repo: Brightspace/node-siren-parser
