sudo: false
language: node_js
node_js:
- '5'
after_success:
- npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: guuL5ZCguWrL5/8i5KHRG2F+dzeGY7G70Ms3zh62Aq5OMXWdPaTcr39ya1fwyaYZNMMG0cDyZ62bV+N/VvdFl4C+HF+paXMjn0+QrVcf/0hHhx6iYxkrr4S7lbFRNvsnyBTGy7XvULD44A5DOkh3sLL0+4ZkN8DsbEsFnjuXsczjkjqE52xd1mng5yqkn09PAz6OZ4Tdq8p6Hfy5ESW6zpkLwj6ICfdox4K7RluH4Rxyehq3avITHvJXQsWo9iAmx3Lm+dEBE5c1A91zmLfQTgqjYFbTU6KuwxVPQmlr2XJ6t+7MYW+q2I8s4933/8xH9x+yBQ/D00STWsPe95DcK0Y05JpY/VMi/5fI6nmtu/KjeR2fveB/remYCnjqZ89/BAdC3raZGsFT/cJR81nP3TCUeiBatTmZrxjk0rJF7KBFTxDjTz0NfHuvt1cKtM4WdedAsjlyHGrfv/qE4jHeTU1qCCvfqrqAUaVU8Olgr6CkC9JPtS3CNtVykaNRwh1CyfUmYMusv0gZnR6ZwzeZh9A2VLSFRmhSrfH330L2CvYQw7VFJOtoTb+FDxcEYOmFpMl0BFpuwnOtSbGdu8jzy6MvI8eGEw1S5sm6qCGkYWm7Z7FdnG6WGscabBj9BVsO6BiqkxEMXBxThiERPL/3v/Jwc4UbS3bdO4q+iHyKqVQ=
  on:
    tags: true
    repo: Brightspace/node-siren-parser
