sudo: false
language: node_js
node_js: stable
after_success:
- npm run report-cov
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [ "x$TRAVIS_TAG" != "x" ] && npm run publish:cdn'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: dk4zdJ4dwFb1wTiMF2XjIn3OQ96yQYf9/DyUzSfOcK2goUlGNkWz9n7yDlD2YdaBmdUqf5b550I4lKypxdnpKUZjZVk0sHmu/4rQTN/f/Ez/8XaIz/MsO/xRJFoIudtLOWq7HsxqY0Q2t/vsj65gGDaWt+Z3z9HfGy6uSE6PQU5RysemQga6+t9PFhFZUvOJkuv/oQ1jvusT+RjTaBJDEiWyVnHI19JAMRyePv9ecldsJ4iRDW99xNh5WamY/ascMM8yUjNiSlADUBMj7IQ1k9jb6XiXiAAQLLyIjgkTItRxeRmC2DB4Yw/nccqRVy83sdh9Fn3FMTvyDGW4iNxr9eoHRiC1On+K2wsWI2F17KPdV18j3hBUuvuBk/XeP8AWpSQaufuBeSobXKPHS9giMBOs9uU+h5FRudkmGhqY2wsTTSezfas1LPkgCqL5MgsB6ZmkzhBewDaq8nfUK/cJPrDlLj0cQmWIWL9rQH9yyrMmKP/w0y7AHAhPMN/YvEoQZvlsIPLX2F0RQig4NLAaI2jD9WC6tOUgjInekLlxdRn2yMkUQTFKW9kWC5iKbgbxTCz8MyP94iZkjIHM3yDyccFwT3yfk9Na4p2Z4GA3G3nSkfIarB3ZBt5sOjdHy/dgQmiffo6uijaaxkI+7D4Z3jEYTCK+ye0bVwHKofyhXLk=
  on:
    tags: true
    repo: Brightspace/node-siren-parser
env:
  global:
  - secure: "HIAm5TRiT0dt2bsEQvTzrQ6y91hnCS1LP7T0iSefiw4Bhje+YEPbemSc28N1Cj07oyRc7nOjAV5bmGr3nyqCUvoy1nYdCVwSiIg77NeuNMcP6Mh3MNrYCp1n6i8ykn1cSJZOJLiNiMZEX4nLBzy9zWD+oftF7f9DEydIvLfQDvAJcYRSuEB3OSJmIVW75joRmiYax89dkEW/ikowsEUjMucZjW6tFrhzr8XfYI0fKykqhpD9L1ZU77NgjUn3L7wMqdwmeu/brMyq6FR6w3DW0bDoSKyZfFnz4Tl9P6p3iOfM7wK0YxJxKKgjVA6EqvGaq7MFHc3LXbhZvWPYNnTmvRspxCvAYO3TwmOB4FUZLDX9kylINw/ajw0gng/K+I6z8cYOUbLIpERzENawSmgstcOafiHLtfjp8B5tBlT1q48K5mgrp05jaXuvmOgz0HdsSMfqOW+bOgn0zCqnHT2xER9Yd7VDSFqP9kcrJsNuYWr7qGJY9tb3nyLC8d7qUweMug4gcn6By6AyPHD6gCLo8FUqaGYTd+0IKp/aJNsmT8yq4p4K1anuN62qL+QhFMMX/b/dJ8LjHhqAHaAHO8ZZymG6bn9CWqqMOr0w/+jB2vVNgJaRQYAsI/OoFcZYtmQLYIhVk7waVg188HvbyVF1l3glkZsm7wrUACt8UAm8xFw="
